### ISSUE TITLE
List gateway error

### ISSUE THREAD

**Issue by kevinresol** [mainflux/loraserver-docker#1]
I got this error when running the [docker-compose file](https://github.com/mainflux/mainflux/blob/2f96df1/lora/brocaar/docker-compose.yml)

`level=error msg="gwmigrate: list gateways error (will retry): rpc error: code = 14 desc = grpc: the connection is unavailable"`

https://github.com/brocaar/lora-app-server/issues/80 seems to suggest that we need two separate postgres database

**Comment by kevinresol** [comment]
hmm... somehow I am getting this now:

```
lora-network-server    | time="2017-07-27T07:49:40Z" level=info msg="grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: Error while dialing dial tcp: lookup lora-app-server on 127.0.0.11:53: no such host"; Reconnecting to {lora-app-server:8001 <nil>}" 
```

**Comment by drasko** [comment]
@kevinresol these files need to be updated for the changes that happened on the LoRa Server side. PLease take a look at other `loraserver-docer` implementations and compare if something could be backported: https://github.com/ceratop/loraserver-docker

Also, none of these implementations is really tight, as we should switch to `FROM SCRATCH` docker containers with multi-stage build to obtain best integration.

**Comment by kevinresol** [comment]
Switched to that image and the docker compose works fine there.

**Comment by janko-isidorovic** [comment]
@kevinresol can we close the issue?

**Comment by kevinresol** [comment]
I am not sure. I used another image doesn't mean this issue is fixed.

**Comment by drasko** [comment]
@janko-isidorovic issue is not fixed. @manuIO is looking at this.
